image:
  repository: ghcr.io/e-lemongrab/osr-bot
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

config:
  twitchUsername: ""
  twitchOauthToken: ""
  twitchClientId: ""
  twitchClientSecret: ""
  twitchRefreshToken: ""
  twitchChannel: ""
  triggerText: "game is restarting"
  responseText: "!play"
  responseDelaySeconds: 45
  minCooldownSeconds: 60
  coordinateCommandText: ""
  postPlayCoordinateDelaySeconds: 5
  deathTriggerText: ""
  deathCoordinateDelaySeconds: 5
  minCoordinateCooldownSeconds: 10

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
